name: BuildersUtilities
version: ${version}
main: xyz.tehbrian.buildersutilities.BuildersUtilities
api-version: 1.16
authors: [ Arcaniax, TehBrian ]
description: A lot of tiny features that help builders do their thing.
softdepend: [ PlotSquared, WorldGuard ]
website: https://github.com/ItsTehBrian/BuildersUtilities
commands:
  advancedfly:
    description: Toggles advanced fly.
    aliases: [ advfly, af ]
    permission: buildersutilities.advancedfly
    usage: /<command>
  armorcolor:
    description: Opens the armor color creator.
    aliases: acc
    permission: buildersutilities.armorcolor
    usage: /<command>
  banner:
    description: Opens the banner creator.
    aliases: bc
    permission: buildersutilities.banner
    usage: /<command>
  buildersutilities:
    description: Opens the options menu.
    aliases: [ butils, bu ]
    permission: buildersutilities.buildersutilities
    usage: /<command>
  nightvision:
    description: Toggles night vision.
    aliases: nv
    permission: buildersutilities.nightvision
    usage: /<command>
  noclip:
    description: Toggles no-clip.
    aliases: nc
    permission: buildersutilities.noclip
    usage: /<command>
permissions:
  buildersutilities.advancedfly:
    description: Permission to use /advancedfly.
    default: op
  buildersutilities.armorcolor:
    description: Permission to use /armorcolor.
    default: true
  buildersutilities.banner:
    description: Permission to use /banner.
    default: true
  buildersutilities.buildersutilities:
    description: Permission to use /buildersutilities.
    default: true
  buildersutilities.nightvision:
    description: Permission to use /nightvision.
    default: true
  buildersutilities.noclip:
    description: Permission to use /noclip.
    default: op
  buildersutilities.reload:
    description: Permission to use /buildersutilities reload.
    default: op
  buildersutilities.tpgm3:
    description: Permission to teleport while in Spectator mode.
    default: true
