name: BuildersUtilities
description: ${description}
authors: [ Arcaniax, TehBrian ]
website: https://github.com/TehBrian/BuildersUtilities

softdepend: [ PlotSquared, WorldGuard ]

version: ${version}
main: dev.tehbrian.buildersutilities.BuildersUtilities
api-version: 1.20

permissions:
  buildersutilities.ability:
    description: Permission to open the ability menu.
    default: true
  buildersutilities.advancedfly:
    description: Permission to use advanced fly.
    default: op
  buildersutilities.armorcolor:
    description: Permission to open the armor color creator.
    default: true
  buildersutilities.banner:
    description: Permission to open the banner creator.
    default: true
  buildersutilities.doubleslabbreak:
    description: Permission to use double slab break.
    default: true
  buildersutilities.glazedterracottarotate:
    description: Permission to use glazed terracotta rotate.
    default: true
  buildersutilities.irondoortoggle:
    description: Permission to use iron door toggle.
    default: true
  buildersutilities.nightvision:
    description: Permission to use night vision.
    default: true
  buildersutilities.noclip:
    description: Permission to use noclip.
    default: op
  buildersutilities.rc:
    description: Permission to run /buildersutilities rc.
    default: op
  buildersutilities.reload:
    description: Permission to run /buildersutilities reload.
    default: op
  buildersutilities.special:
    description: Permission to open the special items menu.
    default: true
  buildersutilities.spectate.entity:
    description: Permission to spectate entities (including players).
    default: true
    children:
      buildersutilities.spectate.player: true
  buildersutilities.spectate.player:
    description: Permission to spectate players.
    default: true
  buildersutilities.spectate.teleport:
    description: Permission to teleport to players via the spectator menu.
    default: true
